// productos.js
// Fuente única de datos de todas las camisetas de selecciones.
// Generado a partir del catálogo de pagePrincipal (PaginaProductos.html).
// Si agregas o modificas camisetas en pagePrincipal, actualiza también este archivo.

const PRODUCTS = [
  {
    "id": "brasil",
    "name": "Brasil",
    "flag": "🇧🇷",
    "rank": "1° 🏆",
    "titles": "5 TÍTULOS MUNDIALES",
    "desc": "La Canarinha, magia, jogo bonito y el máximo referente del fútbol mundial.",
    "tech": "Tecnología Aeroready: Tejido ultra ligero que absorbe el sudor al instante.",
    "fabricTitle": "TELA PREMIUM",
    "fabricSub": "100% poliéster transpirable",
    "price": 59500,
    "oldPrice": 85000,
    "discount": "-30%",
    "stock": 34,
    "historia": "Con 5 estrellas en el pecho, Brasil es la única selección presente en todos los Mundiales. Cuna de Pelé, Ronaldo y Neymar, su camiseta amarilla es sinónimo de espectáculo y magia.",
    "imgFront": "/img/carrito/brasil-front.webp",
    "imgBack": "/img/carrito/brasil-back.webp"
  },
  {
    "id": "alemania",
    "name": "Alemania",
    "flag": "🇩🇪",
    "rank": "2° 🏆",
    "titles": "4 TÍTULOS MUNDIALES",
    "desc": "Disciplina táctica, jerarquía inquebrantable y mentalidad ganadora histórica.",
    "tech": "Tecnología Heat.RDY: Mantiene la frescura en los momentos de máxima exigencia.",
    "fabricTitle": "TELA PREMIUM",
    "fabricSub": "Secado rápido profesional",
    "price": 59500,
    "oldPrice": 85000,
    "discount": "-30%",
    "stock": 28,
    "historia": "La Mannschaft es sinónimo de eficacia y carácter. Cuatro títulos mundiales avalan una escuela de fútbol basada en la disciplina táctica y el trabajo colectivo.",
    "imgFront": "/img/carrito/alemania-front.webp",
    "imgBack": "/img/carrito/alemania-back.webp"
  },
  {
    "id": "italia",
    "name": "Italia",
    "flag": "🇮🇹",
    "rank": "3° 🏆",
    "titles": "4 TÍTULOS MUNDIALES",
    "desc": "La Squadra Azzurra, elegancia defensiva y orgullo competitivo.",
    "tech": "Tecnología DryCell: Expulsa el sudor de la piel para mayor comodidad.",
    "fabricTitle": "TELA PREMIUM",
    "fabricSub": "100% poliéster transpirable",
    "price": 59500,
    "oldPrice": 85000,
    "discount": "-30%",
    "stock": 22,
    "historia": "La Squadra Azzurra ha levantado 4 Copas del Mundo gracias a una defensa histórica y un orgullo competitivo que la caracteriza desde siempre.",
    "imgFront": "/img/carrito/italia-front.webp",
    "imgBack": "/img/carrito/italia-back.webp"
  },
  {
    "id": "argentina",
    "name": "Argentina",
    "flag": "🇦🇷",
    "rank": "4° 🏆",
    "titles": "3 TÍTULOS MUNDIALES",
    "desc": "Pasión albiceleste, talento puro y gloria eterna en el firmamento futbolístico.",
    "tech": "Tecnología Aeroready: Tejido transpirable de alto rendimiento.",
    "fabricTitle": "TELA PREMIUM",
    "fabricSub": "Secado rápido",
    "price": 59500,
    "oldPrice": 85000,
    "discount": "-30%",
    "stock": 41,
    "historia": "Con Maradona y Messi como máximos ídolos, Argentina es una de las selecciones más ganadoras y pasionales del planeta, con 3 estrellas mundiales.",
    "imgFront": "/img/carrito/argentina-front.webp",
    "imgBack": "/img/carrito/argentina-back.webp"
  },
  {
    "id": "francia",
    "name": "Francia",
    "flag": "🇫🇷",
    "rank": "5° 🏆",
    "titles": "2 TÍTULOS MUNDIALES",
    "desc": "Los Bleus, potencia atlética, modernidad y talento desbordante.",
    "tech": "Tecnología Dri-FIT ADV: Combina tejido antihumedad con ingeniería avanzada.",
    "fabricTitle": "TELA PREMIUM",
    "fabricSub": "100% poliéster transpirable",
    "price": 59500,
    "oldPrice": 85000,
    "discount": "-30%",
    "stock": 30,
    "historia": "Les Bleus combinan talento individual y fuerza de equipo. Campeones del mundo en 1998 y 2018, hoy siguen entre las selecciones más temidas.",
    "imgFront": "/img/carrito/francia-front.webp",
    "imgBack": "/img/carrito/francia-back.webp"
  },
  {
    "id": "uruguay",
    "name": "Uruguay",
    "flag": "🇺🇾",
    "rank": "6° 🏆",
    "titles": "2 TÍTULOS MUNDIALES",
    "desc": "La garra charrúa, pioneros y leyenda viviente de las copas del mundo.",
    "tech": "Tecnología Ultraweave: Tejido ultraligero diseñado para velocidad y confort.",
    "fabricTitle": "TELA PREMIUM",
    "fabricSub": "Secado rápido",
    "price": 59500,
    "oldPrice": 85000,
    "discount": "-30%",
    "stock": 19,
    "historia": "La Celeste fue campeona en los dos primeros Mundiales de la historia (1930 y 1950). Un país pequeño con un gigante legado futbolístico.",
    "imgFront": "/img/carrito/uruguay-front.webp",
    "imgBack": "/img/carrito/uruguay-back.webp"
  },
  {
    "id": "inglaterra",
    "name": "Inglaterra",
    "flag": "🏴",
    "rank": "7° 🏆",
    "titles": "1 TÍTULO MUNDIAL",
    "desc": "La cuna del fútbol, tradición, honor y juego directo.",
    "tech": "Tecnología Dri-FIT: Control total de la transpiración corporal.",
    "fabricTitle": "TELA PREMIUM",
    "fabricSub": "100% poliéster transpirable",
    "price": 59500,
    "oldPrice": 85000,
    "discount": "-30%",
    "stock": 25,
    "historia": "Cuna del fútbol moderno y campeona del mundo en 1950. Los Three Lions representan la casa original del deporte rey.",
    "imgFront": "/img/carrito/inglaterra-front.webp",
    "imgBack": "/img/carrito/inglaterra-back.webp"
  },
  {
    "id": "espana",
    "name": "España",
    "flag": "🇪🇸",
    "rank": "8° 🏆",
    "titles": "1 TÍTULO MUNDIAL",
    "desc": "La Furia Roja, tiki-taka, control absoluto y magia técnica.",
    "tech": "Tecnología Aeroready: Máxima transpirabilidad en cada movimiento.",
    "fabricTitle": "TELA PREMIUM",
    "fabricSub": "Secado rápido",
    "price": 59500,
    "oldPrice": 85000,
    "discount": "-30%",
    "stock": 27,
    "historia": "La Furia Roja deslumbró al mundo con el tiki-taka, coronándose campeona mundial en 2010 y bicampeona de Eurocopa en la misma década dorada.",
    "imgFront": "/img/carrito/espana-front.webp",
    "imgBack": "/img/carrito/espana-back.webp"
  },
  {
    "id": "colombia",
    "name": "Colombia",
    "flag": "🇨🇴",
    "rank": "🥇 COPA AMÉRICA",
    "titles": "1 TÍTULO CONTINENTAL (2001)",
    "desc": "La tricolor cafetera: velocidad, gambeta y una hinchada que vibra en cada mundial.",
    "tech": "Tecnología Climacool: Ventilación estratégica en zonas de alta transpiración.",
    "fabricTitle": "TELA PREMIUM",
    "fabricSub": "100% poliéster transpirable",
    "price": 59500,
    "oldPrice": 85000,
    "discount": "-30%",
    "stock": 52,
    "historia": "La tricolor cafetera es una de las selecciones más queridas de Suramérica, símbolo de garra, alegría y una hinchada inigualable.",
    "imgFront": "/img/carrito/colombia-front.webp",
    "imgBack": "/img/carrito/colombia-back.webp"
  },
  {
    "id": "usa",
    "name": "Estados Unidos",
    "flag": "🇺🇸",
    "rank": "🔥 EN ASCENSO",
    "titles": "SIN TÍTULOS FIFA / CONCACAF MAYOR",
    "desc": "El fútbol que crece más rápido en el continente, anfitrión del Mundial 2026 y en plena expansión global.",
    "tech": "Tecnología Vaporknit: Elasticidad multidireccional para máxima libertad de movimiento.",
    "fabricTitle": "TELA PREMIUM",
    "fabricSub": "Secado rápido",
    "price": 59500,
    "oldPrice": 85000,
    "discount": "-30%",
    "stock": 18,
    "historia": "El fútbol de Estados Unidos crece a pasos agigantados, con una base cada vez más sólida y una afición que no para de crecer de cara al Mundial 2026.",
    "imgFront": "/img/carrito/usa-front.webp",
    "imgBack": "/img/carrito/usa-back.webp"
  },
  {
    "id": "mexico",
    "name": "México",
    "flag": "🇲🇽",
    "rank": "🔥 SIN TÍTULOS MUNDIALES",
    "titles": "MÁXIMO CAMPEÓN DE CONCACAF (SIN TÍTULO MUNDIAL)",
    "desc": "El Tri: una de las hinchadas más fieles del mundo y presencia constante en los mundiales.",
    "tech": "Tecnología HeatGear: Regula la temperatura corporal durante el esfuerzo intenso.",
    "fabricTitle": "TELA PREMIUM",
    "fabricSub": "100% poliéster transpirable",
    "price": 59500,
    "oldPrice": 85000,
    "discount": "-30%",
    "stock": 36,
    "historia": "El Tri es historia pura en Concacaf, con presencia en 17 Mundiales y un fervor por la camiseta verde que atraviesa generaciones.",
    "imgFront": "/img/carrito/mexico-front.webp",
    "imgBack": "/img/carrito/mexico-back.webp"
  },
  {
    "id": "costarica",
    "name": "Costa Rica",
    "flag": "🇨🇷",
    "rank": "🔥 SORPRESA MUNDIALISTA",
    "titles": "CUARTOS DE FINAL BRASIL 2014 (SIN TÍTULO MUNDIAL)",
    "desc": "La Sele: orden defensivo, garra centroamericana y una de las mayores sorpresas mundialistas de la historia.",
    "tech": "Tecnología Ultraweave: Tejido ultraligero diseñado para velocidad y confort.",
    "fabricTitle": "TELA PREMIUM",
    "fabricSub": "Secado rápido",
    "price": 59500,
    "oldPrice": 85000,
    "discount": "-30%",
    "stock": 14,
    "historia": "Los Ticos han dado sorpresas históricas en el Mundial, incluyendo un inolvidable cuartos de final en Brasil 2014.",
    "imgFront": "/img/carrito/costarica-front.webp",
    "imgBack": "/img/carrito/costarica-back.webp"
  },
  {
    "id": "canada",
    "name": "Canadá",
    "flag": "🇨🇦",
    "rank": "🔥 EN CRECIMIENTO",
    "titles": "CO-ANFITRIÓN MUNDIAL 2026 (SIN TÍTULO MUNDIAL)",
    "desc": "Los Canucks: velocidad, juventud y un fútbol en plena consolidación de cara al Mundial de casa.",
    "tech": "Tecnología Dri-FIT ADV: Combina tejido antihumedad con ingeniería avanzada.",
    "fabricTitle": "TELA PREMIUM",
    "fabricSub": "100% poliéster transpirable",
    "price": 59500,
    "oldPrice": 85000,
    "discount": "-30%",
    "stock": 12,
    "historia": "La selección canadiense vive un momento histórico, consolidándose como potencia emergente de Concacaf rumbo al Mundial que coorganiza en 2026.",
    "imgFront": "/img/carrito/canada-front.webp",
    "imgBack": "/img/carrito/canada-back.webp"
  },
  {
    "id": "portugal",
    "name": "Portugal",
    "flag": "🇵🇹",
    "rank": "⭐ EUROCOPA",
    "titles": "1 TÍTULO CONTINENTAL (2016)",
    "desc": "Elegancia y talento individual de primer nivel, cuna de generaciones históricas del fútbol europeo.",
    "tech": "Tecnología HeatGear: Regula la temperatura corporal durante el esfuerzo intenso.",
    "fabricTitle": "TELA PREMIUM",
    "fabricSub": "100% poliéster transpirable",
    "price": 59500,
    "oldPrice": 85000,
    "discount": "-30%",
    "stock": 33,
    "historia": "Con Cristiano Ronaldo como máximo referente, Portugal se coronó campeón de Eurocopa 2016 y es hoy una potencia mundial.",
    "imgFront": "/img/carrito/portugal-front.webp",
    "imgBack": "/img/carrito/portugal-back.webp"
  },
  {
    "id": "paisesbajos",
    "name": "Países Bajos",
    "flag": "🇳🇱",
    "rank": "⭐ EUROCOPA",
    "titles": "1 TÍTULO CONTINENTAL (1988)",
    "desc": "La \"Naranja Mecánica\": fútbol total, 3 finales de mundial y una escuela táctica admirada en todo el mundo.",
    "tech": "Tecnología Dri-FIT: Control total de la transpiración corporal.",
    "fabricTitle": "TELA PREMIUM",
    "fabricSub": "Secado rápido",
    "price": 59500,
    "oldPrice": 85000,
    "discount": "-30%",
    "stock": 20,
    "historia": "La Naranja Mecánica revolucionó el fútbol con el 'fútbol total'. Tres finales de Mundial avalan su enorme historia.",
    "imgFront": "/img/carrito/paisesbajos-front.webp",
    "imgBack": "/img/carrito/paisesbajos-back.webp"
  },
  {
    "id": "chile",
    "name": "Chile",
    "flag": "🇨🇱",
    "rank": "🥇 COPA AMÉRICA",
    "titles": "2 TÍTULOS CONTINENTALES (2015, 2016)",
    "desc": "La Roja: intensidad, presión alta y el bicampeonato continental más reciente de Sudamérica.",
    "tech": "Tecnología Climacool: Ventilación estratégica en zonas de alta transpiración.",
    "fabricTitle": "TELA PREMIUM",
    "fabricSub": "100% poliéster transpirable",
    "price": 59500,
    "oldPrice": 85000,
    "discount": "-30%",
    "stock": 24,
    "historia": "La Roja vivió su época dorada con dos títulos consecutivos de Copa América (2015-2016), marcando una generación irrepetible.",
    "imgFront": "/img/carrito/chile-front.webp",
    "imgBack": "/img/carrito/chile-back.webp"
  }
];